name: testing and deplyment
on: push
jobs:
  github_object:
    runs-on: ubuntu-latest
    steps:
      - name: get github object
        run: echo "${{toJSON(github)}}"
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install packages
        run: npm ci
      - name: test code
        run : npm test
  deploy:
    runs-on:  ubuntu-latest
    needs: testing
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install packages
        run: npm ci
      - name: build
        run: npm run build
    


